//! Build-time grammar version pinning for the Witness Mesh rule catalog.
//!
//! Reads `Cargo.lock` at the workspace root and extracts the pinned
//! `tree-sitter-*` grammar versions, writing them as `const` declarations
//! into `$OUT_DIR/grammar_versions.rs` which the rule catalog includes.
//!
//! Why build.rs (not const-by-hand): the rule catalog ships in every
//! `.tr/3.2` pack, and its BLAKE3 is part of the pack hash. Hand-edited
//! version strings can drift from `Cargo.lock`; build.rs reads the same
//! source of truth Cargo uses, so a grammar bump → lockfile change →
//! catalog change → pack hash change. Reproducibility holds.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Grammar crates the catalog pins. The order is alphabetical for the
/// generated file's stable layout (so a grammar bump produces a
/// minimal diff).
const GRAMMARS: &[(&str, &str)] = &[
    ("tree-sitter-bash", "TREE_SITTER_BASH_VERSION"),
    ("tree-sitter-c", "TREE_SITTER_C_VERSION"),
    ("tree-sitter-c-sharp", "TREE_SITTER_C_SHARP_VERSION"),
    ("tree-sitter-cpp", "TREE_SITTER_CPP_VERSION"),
    ("tree-sitter-elixir", "TREE_SITTER_ELIXIR_VERSION"),
    ("tree-sitter-go", "TREE_SITTER_GO_VERSION"),
    ("tree-sitter-haskell", "TREE_SITTER_HASKELL_VERSION"),
    ("tree-sitter-java", "TREE_SITTER_JAVA_VERSION"),
    ("tree-sitter-javascript", "TREE_SITTER_JAVASCRIPT_VERSION"),
    ("tree-sitter-kotlin-ng", "TREE_SITTER_KOTLIN_VERSION"),
    ("tree-sitter-lua", "TREE_SITTER_LUA_VERSION"),
    ("tree-sitter-php", "TREE_SITTER_PHP_VERSION"),
    ("tree-sitter-python", "TREE_SITTER_PYTHON_VERSION"),
    ("tree-sitter-r", "TREE_SITTER_R_VERSION"),
    ("tree-sitter-ruby", "TREE_SITTER_RUBY_VERSION"),
    ("tree-sitter-rust", "TREE_SITTER_RUST_VERSION"),
    ("tree-sitter-scala", "TREE_SITTER_SCALA_VERSION"),
    ("tree-sitter-swift", "TREE_SITTER_SWIFT_VERSION"),
    ("tree-sitter-typescript", "TREE_SITTER_TYPESCRIPT_VERSION"),
];

fn main() {
    // Locate Cargo.lock at the workspace root. This crate lives at
    // `<workspace>/crates/thinkingroot-extract`, so the lockfile is
    // two directories up.
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));
    let lockfile_path = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("crate is nested at least two levels under workspace root")
        .join("Cargo.lock");

    println!("cargo:rerun-if-changed={}", lockfile_path.display());

    let lockfile_text = fs::read_to_string(&lockfile_path).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to read {} — workspace Cargo.lock is required for grammar pinning: {e}",
            lockfile_path.display()
        )
    });

    let lockfile: toml::Value = toml::from_str(&lockfile_text).unwrap_or_else(|e| {
        panic!("build.rs: failed to parse Cargo.lock as TOML: {e}")
    });

    let packages = lockfile
        .get("package")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("build.rs: Cargo.lock missing `[[package]]` array"));

    let mut out = String::from(
        "// Generated by build.rs from Cargo.lock — DO NOT EDIT.\n\
         // Re-run `cargo build` after a grammar version bump.\n\n",
    );

    for (crate_name, const_name) in GRAMMARS {
        let version = packages
            .iter()
            .filter_map(|p| {
                let name = p.get("name")?.as_str()?;
                if name == *crate_name {
                    p.get("version")?.as_str().map(|s| s.to_string())
                } else {
                    None
                }
            })
            .next()
            .unwrap_or_else(|| {
                panic!(
                    "build.rs: grammar `{crate_name}` not found in Cargo.lock — \
                     the rule catalog expects every grammar in the GRAMMARS table to be \
                     a workspace dependency. Either add it to thinkingroot-parse/Cargo.toml \
                     or remove it from build.rs::GRAMMARS."
                )
            });

        out.push_str(&format!(
            "pub const {const_name}: &str = \"{version}\";\n"
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("grammar_versions.rs");
    fs::write(&dest, out).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to write {}: {e}",
            dest.display()
        )
    });
}
