//! `tr-c2pa` — C2PA Content Credentials interop.
//!
//! C2PA is the Coalition for Content Provenance and Authenticity's
//! standard for cryptographically signing assertions about a piece
//! of content (e.g. "this PNG was generated by GPT-4 on
//! 2026-04-27"). The EU AI Act Article 50 (Aug 2026) mandates that
//! AI-generated content be marked as such — C2PA is the de-facto
//! interchange format.
//!
//! This crate gives `.tr` packs a portable bridge to C2PA:
//!
//! - [`ingest_c2pa_from_bytes`] reads a C2PA-signed asset and
//!   extracts its assertions into a [`C2paManifest`] suitable for
//!   embedding into a TR-1 pack's `provenance/` directory.
//! - [`extract_c2pa_claims`] does the inverse — pulls the C2PA
//!   payload out of a TR-1 pack so a downstream tool can re-emit
//!   it.
//! - [`emit_c2pa_for_html`] embeds the C2PA manifest into a piece
//!   of HTML output (per the C2PA HTML profile) so that AI-served
//!   pages remain attributable end-to-end.
//!
//! ## Feature flags
//!
//! Real C2PA support uses the upstream `c2pa` crate, which pulls in
//! libxml2 + openssl + a few hundred transitive deps. The default
//! `tr-c2pa` build is a stub: every public call returns
//! [`Error::FeatureDisabled`]. Enable the real impl with
//! `--features c2pa-impl`.
//!
//! Plan risk R4 (per `docs/2026-04-27-phase-f-trust-verify-design.md`)
//! notes this trade-off: the workspace-default test loop stays fast,
//! and downstream callers opt in to the heavy stack only when they
//! ship C2PA.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// One C2PA assertion as ThinkingRoot stores it. Mirrors the JSON
/// shape used by the upstream `c2pa-rs` crate but with a
/// vocabulary the rest of the workspace reads.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct C2paAssertion {
    /// Assertion label, e.g. `c2pa.actions`, `stds.schema-org.CreativeWork`.
    pub label: String,
    /// Assertion payload as canonical JSON.
    pub payload: serde_json::Value,
}

/// Parsed C2PA manifest carried alongside a `.tr` pack. The actual
/// JUMBF binary is preserved in [`Self::raw`] so a downstream tool
/// can re-emit the bytes verbatim.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct C2paManifest {
    /// Free-form title of the asset the C2PA payload describes.
    pub title: String,
    /// When the assertion bundle was signed (UTC).
    pub signed_at: DateTime<Utc>,
    /// DID (or other identifier) of the signing party. Often a
    /// `did:web:` for AI vendors; a Sigstore certificate subject
    /// identity for keyless signers.
    pub author: String,
    /// Parsed assertions. Order matches the order they appear in
    /// the source manifest.
    pub assertions: Vec<C2paAssertion>,
    /// Raw JUMBF bytes the manifest was parsed from. Empty when the
    /// manifest was synthesised programmatically rather than read
    /// from a binary asset.
    pub raw: Vec<u8>,
}

/// Errors surfaced by `tr-c2pa`.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum Error {
    /// `tr-c2pa` was built without `--features c2pa-impl` and the
    /// caller invoked a function that requires the real C2PA stack.
    #[error("tr-c2pa was built without the `c2pa-impl` feature")]
    FeatureDisabled,

    /// I/O failure reading or writing C2PA payloads.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),

    /// JSON encode/decode failure.
    #[error("serde_json: {0}")]
    Json(#[from] serde_json::Error),

    /// The upstream `c2pa` crate returned an error. Enabled only
    /// when the real impl is active.
    #[cfg(feature = "c2pa-impl")]
    #[error("c2pa: {0}")]
    C2pa(String),

    /// Generic catch-all — kept so callers do not have to enumerate
    /// every upstream failure.
    #[error("tr-c2pa: {0}")]
    Other(String),
}

/// `tr-c2pa`'s `Result` alias.
pub type Result<T> = std::result::Result<T, Error>;

/// Parse a C2PA-signed asset (image, PDF, video, …) and return the
/// embedded manifest. Stub returns [`Error::FeatureDisabled`] when
/// the `c2pa-impl` feature is off.
pub fn ingest_c2pa_from_bytes(_bytes: &[u8]) -> Result<C2paManifest> {
    #[cfg(feature = "c2pa-impl")]
    {
        ingest_impl(_bytes)
    }
    #[cfg(not(feature = "c2pa-impl"))]
    {
        Err(Error::FeatureDisabled)
    }
}

/// Extract any C2PA assertions persisted inside a `.tr` pack at
/// `provenance/c2pa/manifest.json` (canonical TR-1 layout). Returns
/// an empty vec if the pack carries no C2PA payload.
pub fn extract_c2pa_claims(pack: &tr_format::reader::Pack) -> Result<Vec<C2paAssertion>> {
    let Some(bytes) = pack.entry("provenance/c2pa/manifest.json") else {
        return Ok(Vec::new());
    };
    let manifest: C2paManifest = serde_json::from_slice(bytes)?;
    Ok(manifest.assertions)
}

/// Embed a C2PA manifest into a fragment of HTML using the
/// C2PA HTML profile (`<script type="application/c2pa+json">…`).
/// The output is plain UTF-8 HTML the caller can inject into an
/// existing document.
pub fn emit_c2pa_for_html(manifest: &C2paManifest) -> Result<String> {
    let payload = serde_json::to_string(manifest)?;
    Ok(format!(
        "<script type=\"application/c2pa+json\">{payload}</script>",
    ))
}

#[cfg(feature = "c2pa-impl")]
fn ingest_impl(bytes: &[u8]) -> Result<C2paManifest> {
    use c2pa::Reader;

    let reader = Reader::from_bytes(bytes).map_err(|e| Error::C2pa(e.to_string()))?;
    let active = reader
        .active_manifest()
        .ok_or_else(|| Error::C2pa("no active manifest in payload".into()))?;
    let title = active.title().unwrap_or_default().to_string();
    let signed_at = active
        .signature_info()
        .and_then(|s| s.time().and_then(|t| DateTime::parse_from_rfc3339(t).ok()))
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(Utc::now);
    let author = active
        .signature_info()
        .map(|s| s.cert_serial_number().unwrap_or_default().to_string())
        .unwrap_or_default();
    let assertions = active
        .assertions()
        .iter()
        .map(|a| C2paAssertion {
            label: a.label().to_string(),
            payload: a.kind_value().clone(),
        })
        .collect();
    Ok(C2paManifest {
        title,
        signed_at,
        author,
        assertions,
        raw: bytes.to_vec(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn fixture_manifest() -> C2paManifest {
        C2paManifest {
            title: "demo.png".into(),
            signed_at: Utc.with_ymd_and_hms(2026, 4, 27, 12, 0, 0).unwrap(),
            author: "did:web:alice.example".into(),
            assertions: vec![C2paAssertion {
                label: "c2pa.actions".into(),
                payload: serde_json::json!({"actions": [{"action": "c2pa.created"}]}),
            }],
            raw: Vec::new(),
        }
    }

    #[test]
    fn html_emission_includes_payload() {
        let m = fixture_manifest();
        let html = emit_c2pa_for_html(&m).unwrap();
        assert!(html.contains("application/c2pa+json"));
        assert!(html.contains("did:web:alice.example"));
        assert!(html.contains("c2pa.actions"));
    }

    #[test]
    #[cfg(not(feature = "c2pa-impl"))]
    fn ingest_returns_feature_disabled_when_stubbed() {
        let err = ingest_c2pa_from_bytes(&[]).unwrap_err();
        assert!(matches!(err, Error::FeatureDisabled));
    }

    #[test]
    fn extract_returns_empty_when_pack_has_no_c2pa() {
        use semver::Version;
        use tr_format::manifest::Manifest;
        use tr_format::writer::PackBuilder;

        let mut pb = PackBuilder::new(Manifest::new(
            "alice/demo",
            Version::parse("0.1.0").unwrap(),
            "MIT",
        ));
        pb.put_text("artifacts/card.md", "# x").unwrap();
        let bytes = pb.build().unwrap();
        let pack = tr_format::reader::read_bytes(&bytes).unwrap();

        let claims = extract_c2pa_claims(&pack).unwrap();
        assert!(claims.is_empty());
    }
}
