//! Workspace README synthesiser. Deterministic, idempotent, no LLM.
//!
//! Run at compile-end when cache_dirty=true. Output is byte-stable given
//! identical substrate, which is load-bearing because the synthesised
//! string ends up inside `manifest.toml` and contributes to `pack_hash`
//! (BLAKE3) — non-determinism would break content-addressing.
//!
//! Two render paths:
//! - [`synthesise`] produces the full canonical README written to
//!   `.thinkingroot/README.md` (engine-internal view).
//! - [`synthesise_block`] produces only the auto-block delimited by
//!   the [`BEGIN_MARKER`] / [`END_MARKER`] HTML comments, used by
//!   [`merge_into_root_readme`] to maintain the user-facing
//!   `<workspace>/README.md` while preserving hand-written content
//!   above and below the markers.

use chrono::{DateTime, SecondsFormat, Utc};
use std::fmt::Write;

/// Opening marker delimiting the auto-maintained block in the
/// user-facing root README.
pub const BEGIN_MARKER: &str = "<!-- THINKINGROOT:BEGIN -->";
/// Closing marker delimiting the auto-maintained block in the
/// user-facing root README.
pub const END_MARKER: &str = "<!-- THINKINGROOT:END -->";

#[derive(Debug, Clone)]
pub struct ReadmeInputs<'a> {
    pub workspace_name: &'a str,
    pub description: Option<&'a str>,
    pub extracted_at: DateTime<Utc>,
    pub extractor: &'a str,
    pub source_count: u64,
    pub claim_count: u64,
    pub entity_count: u64,
    pub rooted: u64,
    pub attested: u64,
    pub quarantined: u64,
    pub rejected: u64,
    pub top_entities: &'a [TopEntity<'a>],
    pub sources: &'a [SourceLine<'a>],
    pub branches: &'a [BranchLine<'a>],
    pub contradiction_count: u64,
    pub thinkingroot_version: &'a str,
}

#[derive(Debug, Clone)]
pub struct TopEntity<'a> {
    pub name: &'a str,
    pub claim_count: u64,
}

#[derive(Debug, Clone)]
pub struct SourceLine<'a> {
    pub relative_path: &'a str,
    pub claim_count: u64,
}

#[derive(Debug, Clone)]
pub struct BranchLine<'a> {
    pub name: &'a str,
    pub kind: &'a str,
    pub merge_policy: &'a str,
}

#[derive(Debug, thiserror::Error)]
pub enum ReadmeMergeError {
    #[error("malformed THINKINGROOT markers in root README: {detail}")]
    MalformedMarkers { detail: String },
}

/// Full canonical README, written verbatim to `.thinkingroot/README.md`.
pub fn synthesise(inputs: &ReadmeInputs<'_>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {}", inputs.workspace_name);
    out.push('\n');
    if let Some(desc) = inputs.description {
        let _ = writeln!(out, "> {desc}");
        out.push('\n');
    }
    let _ = writeln!(
        out,
        "Compiled {} by {}.",
        inputs
            .extracted_at
            .to_rfc3339_opts(SecondsFormat::Secs, true),
        inputs.extractor,
    );
    out.push('\n');
    write_sections(&mut out, inputs);
    out.push_str("## How to use\n\n");
    out.push_str("```bash\n");
    let _ = writeln!(
        out,
        "root mount ./{}.tr",
        slug_from_workspace_name(inputs.workspace_name),
    );
    out.push_str("```\n\n");
    out.push_str("---\n");
    let _ = writeln!(
        out,
        "*Auto-generated by ThinkingRoot {}. Edit `<workspace>/README.md` to override.*",
        inputs.thinkingroot_version,
    );
    out
}

/// The auto-block content, delimited by [`BEGIN_MARKER`] and
/// [`END_MARKER`]. Suitable for splicing into a user-facing root README
/// via [`merge_into_root_readme`].
pub fn synthesise_block(inputs: &ReadmeInputs<'_>) -> String {
    let mut out = String::new();
    out.push_str(BEGIN_MARKER);
    out.push('\n');
    let _ = writeln!(
        out,
        "_Auto-generated by ThinkingRoot {} on {}. Edits between these markers will be overwritten on the next compile — put hand-written content above or below this block._",
        inputs.thinkingroot_version,
        inputs
            .extracted_at
            .to_rfc3339_opts(SecondsFormat::Secs, true),
    );
    out.push('\n');
    write_sections(&mut out, inputs);
    out.push_str(END_MARKER);
    out
}

/// Merge a freshly-synthesised auto-block into whatever the user
/// currently has at `<workspace>/README.md`, preserving hand-written
/// content outside the markers byte-for-byte.
///
/// Behaviour:
/// - `existing == None` → returns `default_if_missing` unchanged.
/// - both markers absent → appends `\n\n{block}\n` to the existing
///   contents, preserving the prefix verbatim.
/// - both markers present, balanced (one each, BEGIN before END) →
///   replaces only the bytes between (and including) the markers; the
///   prefix and suffix are byte-preserved.
/// - any other shape (multiple BEGINs, multiple ENDs, missing one,
///   END before BEGIN) → returns [`ReadmeMergeError::MalformedMarkers`].
///   The caller is expected to log a warning and leave the file
///   untouched (no silent failure — see CLAUDE.md honesty rules).
pub fn merge_into_root_readme(
    existing: Option<&str>,
    block: &str,
    default_if_missing: &str,
) -> Result<String, ReadmeMergeError> {
    let Some(existing) = existing else {
        return Ok(default_if_missing.to_string());
    };

    let begin_count = existing.matches(BEGIN_MARKER).count();
    let end_count = existing.matches(END_MARKER).count();

    match (begin_count, end_count) {
        (0, 0) => {
            let mut out = String::with_capacity(existing.len() + block.len() + 4);
            out.push_str(existing);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            if !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(block);
            if !block.ends_with('\n') {
                out.push('\n');
            }
            Ok(out)
        }
        (1, 1) => {
            let begin_pos = existing.find(BEGIN_MARKER).expect("count == 1");
            let end_pos = existing.find(END_MARKER).expect("count == 1");
            if begin_pos > end_pos {
                return Err(ReadmeMergeError::MalformedMarkers {
                    detail: "END marker appears before BEGIN".into(),
                });
            }
            let end_close = end_pos + END_MARKER.len();
            let mut out = String::with_capacity(
                existing.len().saturating_sub(end_close - begin_pos) + block.len(),
            );
            out.push_str(&existing[..begin_pos]);
            out.push_str(block);
            out.push_str(&existing[end_close..]);
            Ok(out)
        }
        _ => Err(ReadmeMergeError::MalformedMarkers {
            detail: format!(
                "expected exactly 1 BEGIN and 1 END marker, found {begin_count} BEGIN and {end_count} END",
            ),
        }),
    }
}

fn write_sections(out: &mut String, inputs: &ReadmeInputs<'_>) {
    out.push_str("## Overview\n\n");
    let _ = writeln!(
        out,
        "- **{}** sources · **{}** claims · **{}** entities",
        inputs.source_count, inputs.claim_count, inputs.entity_count,
    );
    let total_tier = inputs.rooted + inputs.attested + inputs.quarantined + inputs.rejected;
    if total_tier > 0 {
        let _ = writeln!(
            out,
            "- Trust: {}% rooted, {}% attested, {}% quarantined, {}% rejected",
            pct(inputs.rooted, total_tier),
            pct(inputs.attested, total_tier),
            pct(inputs.quarantined, total_tier),
            pct(inputs.rejected, total_tier),
        );
    }
    let _ = writeln!(out, "- {} open contradictions", inputs.contradiction_count);
    out.push('\n');

    out.push_str("## Top entities\n\n");
    if inputs.top_entities.is_empty() {
        out.push_str("_No entities yet._\n\n");
    } else {
        for e in inputs.top_entities {
            let _ = writeln!(out, "- {} — {} claims", escape_inline(e.name), e.claim_count);
        }
        out.push('\n');
    }

    out.push_str("## Sources\n\n");
    if inputs.sources.is_empty() {
        out.push_str("_No sources yet._\n\n");
    } else {
        out.push_str("| Path | Claims |\n");
        out.push_str("| --- | ---: |\n");
        for s in inputs.sources {
            let _ = writeln!(
                out,
                "| {} | {} |",
                escape_table_cell(s.relative_path),
                s.claim_count,
            );
        }
        out.push('\n');
    }

    out.push_str("## Branches\n\n");
    if inputs.branches.is_empty() {
        out.push_str("Only `main`.\n\n");
    } else {
        for b in inputs.branches {
            let _ = writeln!(
                out,
                "- `{}` — kind: {}, merge policy: {}",
                escape_inline(b.name),
                escape_inline(b.kind),
                escape_inline(b.merge_policy),
            );
        }
        out.push('\n');
    }
}

fn pct(n: u64, total: u64) -> u64 {
    if total == 0 { 0 } else { n * 100 / total }
}

/// Convert a workspace name (which may contain `owner/slug` or arbitrary
/// characters) into a filesystem-safe slug for the `root mount` example
/// command in the canonical README.
fn slug_from_workspace_name(name: &str) -> String {
    let tail = name.rsplit('/').next().unwrap_or(name);
    tail.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

/// Escape characters that would break inline markdown emphasis.
fn escape_inline(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '|' => out.push_str("\\|"),
            '*' => out.push_str("\\*"),
            '_' => out.push_str("\\_"),
            '`' => out.push_str("\\`"),
            _ => out.push(c),
        }
    }
    out
}

/// Escape characters that would break a markdown table cell.
fn escape_table_cell(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '|' => out.push_str("\\|"),
            '\n' | '\r' => out.push_str("<br>"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn fixed_inputs() -> (
        Vec<TopEntity<'static>>,
        Vec<SourceLine<'static>>,
        Vec<BranchLine<'static>>,
    ) {
        (
            vec![
                TopEntity { name: "PaymentService", claim_count: 42 },
                TopEntity { name: "OrderRouter", claim_count: 31 },
            ],
            vec![
                SourceLine {
                    relative_path: "src/lib.rs",
                    claim_count: 28,
                },
                SourceLine {
                    relative_path: "docs/architecture.md",
                    claim_count: 15,
                },
            ],
            vec![BranchLine {
                name: "feature/auth-rewrite",
                kind: "User",
                merge_policy: "RequiresProposal",
            }],
        )
    }

    fn build<'a>(
        ents: &'a [TopEntity<'a>],
        srcs: &'a [SourceLine<'a>],
        brs: &'a [BranchLine<'a>],
    ) -> ReadmeInputs<'a> {
        ReadmeInputs {
            workspace_name: "acme/checkout",
            description: Some("Checkout service knowledge graph"),
            extracted_at: Utc.with_ymd_and_hms(2026, 5, 9, 12, 30, 0).unwrap(),
            extractor: "thinkingroot/extract@0.9.1",
            source_count: 142,
            claim_count: 4_891,
            entity_count: 1_203,
            rooted: 870,
            attested: 110,
            quarantined: 18,
            rejected: 2,
            top_entities: ents,
            sources: srcs,
            branches: brs,
            contradiction_count: 3,
            thinkingroot_version: "0.9.1",
        }
    }

    #[test]
    fn synth_is_deterministic_for_identical_inputs() {
        let (ents, srcs, brs) = fixed_inputs();
        let inputs = build(&ents, &srcs, &brs);
        let a = synthesise(&inputs);
        let b = synthesise(&inputs);
        assert_eq!(a, b, "synthesise must be byte-stable");
        let block_a = synthesise_block(&inputs);
        let block_b = synthesise_block(&inputs);
        assert_eq!(block_a, block_b, "synthesise_block must be byte-stable");
    }

    #[test]
    fn synth_includes_all_required_sections() {
        let (ents, srcs, brs) = fixed_inputs();
        let out = synthesise(&build(&ents, &srcs, &brs));
        for needle in [
            "# acme/checkout",
            "> Checkout service knowledge graph",
            "Compiled 2026-05-09T12:30:00Z by thinkingroot/extract@0.9.1.",
            "## Overview",
            "**142** sources · **4891** claims · **1203** entities",
            "Trust: 87% rooted, 11% attested, 1% quarantined, 0% rejected",
            "3 open contradictions",
            "## Top entities",
            "PaymentService — 42 claims",
            "## Sources",
            "| src/lib.rs | 28 |",
            "## Branches",
            "feature/auth-rewrite",
            "## How to use",
            "root mount ./checkout.tr",
            "*Auto-generated by ThinkingRoot 0.9.1.",
        ] {
            assert!(out.contains(needle), "missing {needle:?} in:\n{out}");
        }
    }

    #[test]
    fn synth_handles_zero_branches_zero_contradictions() {
        let inputs = ReadmeInputs {
            workspace_name: "empty",
            description: None,
            extracted_at: Utc.with_ymd_and_hms(2026, 5, 9, 0, 0, 0).unwrap(),
            extractor: "thinkingroot/extract@0.9.1",
            source_count: 0,
            claim_count: 0,
            entity_count: 0,
            rooted: 0,
            attested: 0,
            quarantined: 0,
            rejected: 0,
            top_entities: &[],
            sources: &[],
            branches: &[],
            contradiction_count: 0,
            thinkingroot_version: "0.9.1",
        };
        let out = synthesise(&inputs);
        assert!(out.contains("_No entities yet._"));
        assert!(out.contains("_No sources yet._"));
        assert!(out.contains("Only `main`."));
        assert!(out.contains("0 open contradictions"));
        assert!(
            !out.contains("Trust:"),
            "trust line should be omitted when no claims have a tier",
        );
    }

    #[test]
    fn synth_escapes_pipe_in_source_paths() {
        let srcs = vec![SourceLine {
            relative_path: "weird|path.md",
            claim_count: 1,
        }];
        let inputs = build(&[], &srcs, &[]);
        let out = synthesise(&inputs);
        assert!(out.contains("| weird\\|path.md | 1 |"));
        assert!(!out.contains("| weird|path.md |"));
    }

    #[test]
    fn merge_creates_file_when_existing_is_none() {
        let block = synthesise_block(&build(&[], &[], &[]));
        let default = format!("# my-ws\n\n{block}\n");
        let merged = merge_into_root_readme(None, &block, &default).unwrap();
        assert_eq!(merged, default);
    }

    #[test]
    fn merge_appends_block_when_markers_absent() {
        let block = synthesise_block(&build(&[], &[], &[]));
        let existing = "# My Project\n\nHand-written intro.\n";
        let merged = merge_into_root_readme(Some(existing), &block, "").unwrap();
        assert!(merged.starts_with("# My Project\n\nHand-written intro.\n"));
        assert!(merged.contains(BEGIN_MARKER));
        assert!(merged.contains(END_MARKER));
        assert!(merged.ends_with('\n'));
    }

    #[test]
    fn merge_replaces_between_markers_preserving_top_and_tail() {
        let (ents, srcs, brs) = fixed_inputs();
        let new_block = synthesise_block(&build(&ents, &srcs, &brs));
        let existing = format!(
            "# My Project\n\nHand-written intro that I own.\n\n{BEGIN_MARKER}\n_old auto content_\n{END_MARKER}\n\n## License\n\nMIT — hand-written tail.\n",
        );
        let merged = merge_into_root_readme(Some(&existing), &new_block, "").unwrap();
        assert!(merged.starts_with("# My Project\n\nHand-written intro that I own.\n\n"));
        assert!(merged.ends_with("\n\n## License\n\nMIT — hand-written tail.\n"));
        assert!(merged.contains("PaymentService — 42 claims"));
        assert!(!merged.contains("_old auto content_"));
        assert_eq!(merged.matches(BEGIN_MARKER).count(), 1);
        assert_eq!(merged.matches(END_MARKER).count(), 1);
    }

    #[test]
    fn merge_rejects_unbalanced_markers() {
        let block = synthesise_block(&build(&[], &[], &[]));
        let existing = format!("hi\n{BEGIN_MARKER}\n");
        let err = merge_into_root_readme(Some(&existing), &block, "")
            .expect_err("must reject unbalanced markers");
        assert!(matches!(err, ReadmeMergeError::MalformedMarkers { .. }));
    }

    #[test]
    fn merge_rejects_end_before_begin() {
        let block = synthesise_block(&build(&[], &[], &[]));
        let existing = format!("{END_MARKER}\nbody\n{BEGIN_MARKER}\n");
        let err = merge_into_root_readme(Some(&existing), &block, "")
            .expect_err("must reject END before BEGIN");
        match err {
            ReadmeMergeError::MalformedMarkers { detail } => {
                assert!(detail.contains("END marker appears before BEGIN"), "got {detail}");
            }
        }
    }

    #[test]
    fn merge_idempotent() {
        let (ents, srcs, brs) = fixed_inputs();
        let block = synthesise_block(&build(&ents, &srcs, &brs));
        let existing = format!(
            "# Hi\n\nIntro.\n\n{BEGIN_MARKER}\nold\n{END_MARKER}\n\nTail.\n",
        );
        let once = merge_into_root_readme(Some(&existing), &block, "").unwrap();
        let twice = merge_into_root_readme(Some(&once), &block, "").unwrap();
        assert_eq!(once, twice, "merge must be idempotent on repeat application");
    }
}
