"""Type stubs for the native ThinkingRoot extension module."""

from typing import Any, Optional

class ThinkingRootError(Exception): ...

def compile(path: str) -> dict[str, Any]: ...
def parse_directory(path: str) -> list[dict[str, Any]]: ...
def parse_file(path: str) -> dict[str, Any]: ...
def open(path: str) -> Engine: ...

class Engine:
    @property
    def session_id(self) -> str: ...
    def get_entities(self) -> list[dict[str, Any]]: ...
    def get_entity(self, name: str) -> dict[str, Any]: ...
    def get_claims(
        self,
        type: Optional[str] = None,
        min_confidence: Optional[float] = None,
    ) -> list[dict[str, Any]]: ...
    def get_relations(self, entity: str) -> list[dict[str, Any]]: ...
    def get_all_relations(self) -> list[dict[str, Any]]: ...
    def search(self, query: str, top_k: Optional[int] = None) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def verify(self) -> dict[str, Any]: ...
    def get_sources(self) -> list[dict[str, Any]]: ...
    def get_contradictions(self) -> dict[str, Any]: ...
    # Hybrid Retrieval (post-2026-05-03)
    def hybrid_search(
        self,
        query: str,
        top_k: Optional[int] = None,
        require_certificate: Optional[bool] = None,
        include_quarantined: Optional[bool] = None,
        require_provenance_verified: Optional[bool] = None,
    ) -> dict[str, Any]: ...
    # RARP / Active Engram Protocol (post-2026-05-03)
    def materialize_engram(
        self,
        topic: str,
        seed_entity_ids: Optional[list[str]] = None,
        scope: Optional[dict[str, Any]] = None,
    ) -> dict[str, Any]: ...
    def probe_engram(
        self,
        pointer: str,
        question: str,
        clearance: Optional[list[str]] = None,
        probe_kind: Optional[str] = None,
        score_with_hybrid: Optional[bool] = None,
    ) -> dict[str, Any]: ...
    def list_engrams(self) -> list[dict[str, Any]]: ...
    def expire_engram(self, pointer: str) -> bool: ...
    def reset_session(self) -> None: ...
