//! `root init` — scaffold `tr-pack.toml` for the publish flow.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, anyhow};
use console::style;

use super::config;

pub const MANIFEST_NAME: &str = "tr-pack.toml";

pub async fn run(
    slug: Option<String>,
    owner: Option<String>,
    server_override: Option<String>,
) -> Result<()> {
    let manifest_path = Path::new(".").join(MANIFEST_NAME);
    if manifest_path.exists() {
        return Err(anyhow!(
            "{} already exists in this directory",
            MANIFEST_NAME
        ));
    }

    let cfg = config::load_or_default(server_override.as_deref())?;

    let slug = slug
        .or_else(|| {
            std::env::current_dir()
                .ok()
                .and_then(|p| p.file_name().map(|n| n.to_string_lossy().into_owned()))
        })
        .ok_or_else(|| anyhow!("could not infer slug from current directory"))?;
    sanity_check_slug(&slug)?;

    let owner = match owner {
        Some(o) => o,
        None => cfg
            .handle
            .clone()
            .ok_or_else(|| anyhow!("not logged in and no --owner provided"))?,
    };

    let manifest = format!(
        "# tr-pack.toml — generated by `root init` on {date}\n\
         #\n\
         # `root publish` reads this manifest, tarballs the directory\n\
         # excluding paths in `exclude`, uploads to the cloud, and\n\
         # registers a new pack version under {{owner}}/{{slug}}.\n\
         \n\
         [pack]\n\
         owner = \"{owner}\"\n\
         slug = \"{slug}\"\n\
         description = \"\"\n\
         license = \"Apache-2.0\"\n\
         visibility = \"public\"\n\
         \n\
         [publish]\n\
         # File globs to exclude from the tarball, relative to the\n\
         # workspace root. The CLI always excludes:\n\
         #   .git/, .thinkingroot/, target/, node_modules/\n\
         exclude = []\n",
        date = chrono::Utc::now().to_rfc3339(),
        owner = owner,
        slug = slug,
    );
    fs::write(&manifest_path, manifest)
        .with_context(|| format!("write {}", manifest_path.display()))?;

    println!(
        "{} wrote {}",
        style("✓").green(),
        style(manifest_path.display()).bold()
    );
    println!("  pack: {}/{}", style(&owner).bold(), style(&slug).bold());
    println!("  next: {}", style("root publish").cyan());
    Ok(())
}

pub fn sanity_check_slug(s: &str) -> Result<()> {
    if s.is_empty() || s.len() > 64 {
        return Err(anyhow!("slug must be 1–64 characters"));
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(anyhow!(
            "slug must be alphanumeric / dash / underscore (got `{s}`)"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanity_check_slug_accepts_typical_names() {
        for ok in ["demo", "my-pack", "my_pack", "hello-world-1", "a"] {
            sanity_check_slug(ok).unwrap();
        }
    }

    #[test]
    fn sanity_check_slug_rejects_invalid() {
        for bad in ["", "with spaces", "with/slash", "with.dot", &"x".repeat(65)] {
            assert!(sanity_check_slug(bad).is_err(), "should reject `{bad}`");
        }
    }
}
