//! Golden-bytes lockdown for the v3 manifest canonicalization rule.
//!
//! Per the v3 implementation plan
//! (`~/.claude/plans/zippy-wiggling-pelican.md`) decision **D7**:
//!
//!   > Pack hash canonicalization rule: lock in Week 2, golden-vector
//!   > test before Week 3 starts. Sigstore signing in Week 3 builds on
//!   > these bytes; changing the rule afterward invalidates every
//!   > previously-signed pack.
//!
//! This test fixes the exact byte sequence the v3 writer produces for a
//! fixed-input manifest. Any change to:
//!
//!   - field ordering in `ManifestV3::emit_canonical_toml`
//!   - quoting/escaping rules
//!   - line endings
//!   - trailing whitespace handling
//!
//! …trips the assertion. If a change is intentional and v3 has not yet
//! shipped a signed pack to anyone, the constant in this test can be
//! regenerated by uncommenting the `eprintln!` line below and running
//! `cargo test`. After Week 3 starts producing signed packs in the
//! wild, **do not regenerate** — change the test, ship a new format
//! version (`tr/4`).

use semver::Version;
use tr_format::{ClaimRecord, ManifestV3, V3PackBuilder, digest::blake3_hex};

/// The fixed-input manifest for the golden test. Hard-coded values
/// chosen to exercise: required fields, optional strings, optional
/// numbers, and the authors array.
fn fixture_manifest() -> ManifestV3 {
    let mut m = ManifestV3::new("alice/golden", Version::parse("1.0.0").unwrap());
    m.source_hash = "blake3:00000000000000000000000000000000".into();
    m.claims_hash = "blake3:11111111111111111111111111111111".into();
    m.pack_hash = "blake3:22222222222222222222222222222222".into();
    m.source_files = Some(2);
    m.source_bytes = Some(42);
    m.claim_count = Some(3);
    m.extractor = Some("thinkingroot/extract@0.9.1".into());
    m.license = Some("MIT".into());
    m.description = Some("golden-bytes fixture".into());
    m.authors = vec!["alice@example.com".into(), "bob@example.com".into()];
    m
}

/// The locked canonical TOML bytes for `fixture_manifest()`. Alphabetical
/// key order, basic-string escaping, no trailing whitespace, LF line
/// endings. Includes `pack_hash` as set on the input.
const FIXTURE_CANONICAL_TOML: &str = "\
authors = [\"alice@example.com\", \"bob@example.com\"]
claim_count = 3
claims_hash = \"blake3:11111111111111111111111111111111\"
description = \"golden-bytes fixture\"
extractor = \"thinkingroot/extract@0.9.1\"
format_version = \"tr/3\"
license = \"MIT\"
name = \"alice/golden\"
pack_hash = \"blake3:22222222222222222222222222222222\"
source_bytes = 42
source_files = 2
source_hash = \"blake3:00000000000000000000000000000000\"
version = \"1.0.0\"
";

/// Same as above with `pack_hash` blanked — the bytes that go into the
/// BLAKE3 pack-hash recipe per spec §3.1 / §16.1.
const FIXTURE_HASH_INPUT_TOML: &str = "\
authors = [\"alice@example.com\", \"bob@example.com\"]
claim_count = 3
claims_hash = \"blake3:11111111111111111111111111111111\"
description = \"golden-bytes fixture\"
extractor = \"thinkingroot/extract@0.9.1\"
format_version = \"tr/3\"
license = \"MIT\"
name = \"alice/golden\"
pack_hash = \"\"
source_bytes = 42
source_files = 2
source_hash = \"blake3:00000000000000000000000000000000\"
version = \"1.0.0\"
";

#[test]
fn manifest_canonical_toml_is_byte_stable() {
    let m = fixture_manifest();
    let actual = m.to_canonical_toml();
    let actual_str = std::str::from_utf8(&actual).expect("canonical TOML must be UTF-8");

    if actual_str != FIXTURE_CANONICAL_TOML {
        // eprintln to ease intentional regen *before* shipping signed
        // packs — see module doc. Uncomment + rerun if a deliberate
        // canonicalization change is in flight.
        eprintln!("=== ACTUAL (paste into FIXTURE_CANONICAL_TOML) ===\n{actual_str}");
    }
    assert_eq!(
        actual_str, FIXTURE_CANONICAL_TOML,
        "manifest canonical TOML drifted — see module doc for D7 lock"
    );
}

#[test]
fn manifest_hash_input_blanks_pack_hash() {
    let m = fixture_manifest();
    let actual = m.canonical_bytes_for_hashing();
    let actual_str = std::str::from_utf8(&actual).expect("hash-input must be UTF-8");
    assert_eq!(
        actual_str, FIXTURE_HASH_INPUT_TOML,
        "canonical_bytes_for_hashing drifted — D7 lock breached"
    );
    assert!(
        !actual_str.contains("blake3:22222222222222222222222222222222"),
        "pack_hash must be blanked in hashing-input bytes"
    );
}

#[test]
fn manifest_canonical_round_trips_through_parse() {
    let m = fixture_manifest();
    let canonical = m.to_canonical_toml();
    let parsed = ManifestV3::parse(&canonical).expect("canonical TOML must parse");
    assert_eq!(parsed.name, m.name);
    assert_eq!(parsed.version, m.version);
    assert_eq!(parsed.source_hash, m.source_hash);
    assert_eq!(parsed.claims_hash, m.claims_hash);
    assert_eq!(parsed.pack_hash, m.pack_hash);
    assert_eq!(parsed.source_files, m.source_files);
    assert_eq!(parsed.source_bytes, m.source_bytes);
    assert_eq!(parsed.claim_count, m.claim_count);
    assert_eq!(parsed.license, m.license);
    assert_eq!(parsed.description, m.description);
    assert_eq!(parsed.extractor, m.extractor);
    assert_eq!(parsed.authors, m.authors);
}

#[test]
fn pack_hash_recipe_is_locked() {
    // Synthetic, deterministic pack: known manifest + known source +
    // known claim. The pack_hash output is computed from the recipe
    // `BLAKE3(canonical_manifest || NUL || source.tar.zst || NUL ||
    // claims.jsonl)`. We can't pin the *raw bytes* of source.tar.zst
    // (zstd output may shift across library versions), so this test
    // anchors a different invariant: the *recipe* itself, by
    // recomputing the hash from the components extracted from the
    // emitted pack and comparing to the manifest's declared
    // `pack_hash`.
    use std::io::Read;

    let mut b = V3PackBuilder::new(ManifestV3::new(
        "alice/recipe",
        Version::parse("1.0.0").unwrap(),
    ));
    b.add_source_file("hello.md", b"# Hello\n").unwrap();
    b.add_claim(ClaimRecord::new(
        "c-1",
        "Greeting",
        vec!["Hello".into()],
        "hello.md",
        0,
        8,
    ));
    let pack_bytes = b.build().unwrap();

    // Re-extract manifest.toml, source.tar.zst, claims.jsonl from the pack.
    let mut manifest_bytes: Vec<u8> = Vec::new();
    let mut source_archive_bytes: Vec<u8> = Vec::new();
    let mut claims_jsonl_bytes: Vec<u8> = Vec::new();
    let mut archive = tar::Archive::new(std::io::Cursor::new(&pack_bytes));
    for entry in archive.entries().unwrap() {
        let mut entry = entry.unwrap();
        let path = entry.path().unwrap().to_string_lossy().into_owned();
        let mut buf = Vec::new();
        entry.read_to_end(&mut buf).unwrap();
        match path.as_str() {
            "manifest.toml" => manifest_bytes = buf,
            "source.tar.zst" => source_archive_bytes = buf,
            "claims.jsonl" => claims_jsonl_bytes = buf,
            other => panic!("unexpected entry: {other}"),
        }
    }
    assert!(!manifest_bytes.is_empty());
    assert!(!source_archive_bytes.is_empty());
    assert!(!claims_jsonl_bytes.is_empty());

    let parsed = ManifestV3::parse(&manifest_bytes).unwrap();

    // Recompute pack_hash via the recipe.
    let canonical_for_hashing = {
        let mut clone = parsed.clone();
        clone.pack_hash = String::new();
        clone.to_canonical_toml()
    };
    let mut input = Vec::with_capacity(
        canonical_for_hashing.len() + 1 + source_archive_bytes.len() + 1 + claims_jsonl_bytes.len(),
    );
    input.extend_from_slice(&canonical_for_hashing);
    input.push(0);
    input.extend_from_slice(&source_archive_bytes);
    input.push(0);
    input.extend_from_slice(&claims_jsonl_bytes);
    let recomputed = format!("blake3:{}", blake3_hex(&input));

    assert_eq!(
        parsed.pack_hash, recomputed,
        "pack_hash recipe drifted: producer-side recipe must match \
         the verifier-side recipe (spec §3.1 / §16.1)"
    );
}
